// Stdlib.metal
// Generated by gyb - do not edit directly
// Run: gyb --line-directive '' -o Stdlib.metal Stdlib.metal.gyb

#include <metal_stdlib>
using namespace metal;

namespace shadergraph {

// ============================================================================
// MARK: - Arithmetic Operations (Generated)
// ============================================================================

// --- float scalar-scalar ---
[[stitchable]] float add_f_f(float a, float b) { return a + b; }
[[stitchable]] float sub_f_f(float a, float b) { return a - b; }
[[stitchable]] float mul_f_f(float a, float b) { return a * b; }
[[stitchable]] float div_f_f(float a, float b) { return a / b; }

// --- float2 vector-vector ---
[[stitchable]] float2 add_f2_f2(float2 a, float2 b) { return a + b; }
[[stitchable]] float2 sub_f2_f2(float2 a, float2 b) { return a - b; }
[[stitchable]] float2 mul_f2_f2(float2 a, float2 b) { return a * b; }
[[stitchable]] float2 div_f2_f2(float2 a, float2 b) { return a / b; }

// --- float2 vector-scalar ---
[[stitchable]] float2 add_f2_f(float2 a, float b) { return a + b; }
[[stitchable]] float2 sub_f2_f(float2 a, float b) { return a - b; }
[[stitchable]] float2 mul_f2_f(float2 a, float b) { return a * b; }
[[stitchable]] float2 div_f2_f(float2 a, float b) { return a / b; }

// --- float2 swizzles ---
[[stitchable]] float swizzle_x_f2(float2 v) { return v.x; }
[[stitchable]] float swizzle_y_f2(float2 v) { return v.y; }

// --- float3 vector-vector ---
[[stitchable]] float3 add_f3_f3(float3 a, float3 b) { return a + b; }
[[stitchable]] float3 sub_f3_f3(float3 a, float3 b) { return a - b; }
[[stitchable]] float3 mul_f3_f3(float3 a, float3 b) { return a * b; }
[[stitchable]] float3 div_f3_f3(float3 a, float3 b) { return a / b; }

// --- float3 vector-scalar ---
[[stitchable]] float3 add_f3_f(float3 a, float b) { return a + b; }
[[stitchable]] float3 sub_f3_f(float3 a, float b) { return a - b; }
[[stitchable]] float3 mul_f3_f(float3 a, float b) { return a * b; }
[[stitchable]] float3 div_f3_f(float3 a, float b) { return a / b; }

// --- float3 swizzles ---
[[stitchable]] float swizzle_x_f3(float3 v) { return v.x; }
[[stitchable]] float swizzle_y_f3(float3 v) { return v.y; }
[[stitchable]] float swizzle_z_f3(float3 v) { return v.z; }

// --- float4 vector-vector ---
[[stitchable]] float4 add_f4_f4(float4 a, float4 b) { return a + b; }
[[stitchable]] float4 sub_f4_f4(float4 a, float4 b) { return a - b; }
[[stitchable]] float4 mul_f4_f4(float4 a, float4 b) { return a * b; }
[[stitchable]] float4 div_f4_f4(float4 a, float4 b) { return a / b; }

// --- float4 vector-scalar ---
[[stitchable]] float4 add_f4_f(float4 a, float b) { return a + b; }
[[stitchable]] float4 sub_f4_f(float4 a, float b) { return a - b; }
[[stitchable]] float4 mul_f4_f(float4 a, float b) { return a * b; }
[[stitchable]] float4 div_f4_f(float4 a, float b) { return a / b; }

// --- float4 swizzles ---
[[stitchable]] float swizzle_x_f4(float4 v) { return v.x; }
[[stitchable]] float swizzle_y_f4(float4 v) { return v.y; }
[[stitchable]] float swizzle_z_f4(float4 v) { return v.z; }
[[stitchable]] float swizzle_w_f4(float4 v) { return v.w; }


// ============================================================================
// MARK: - Math Functions
// ============================================================================

[[stitchable]] float sin_f(float x) { return sin(x); }
[[stitchable]] float cos_f(float x) { return cos(x); }

[[stitchable]] float mix_f(float a, float b, float t) { return mix(a, b, t); }
[[stitchable]] float4 mix_f4(float4 a, float4 b, float t) { return mix(a, b, t); }

// Fused multiply-add: a * b + c
[[stitchable]] float fma_f(float a, float b, float c) { return fma(a, b, c); }
[[stitchable]] float4 fma_f4(float4 a, float4 b, float4 c) { return fma(a, b, c); }
[[stitchable]] float4 fma_f4_f(float4 a, float b, float4 c) { return fma(a, float4(b), c); }

// ============================================================================
// MARK: - Construction
// ============================================================================

[[stitchable]] float4 make_f4(float x, float y, float z, float w) { return float4(x, y, z, w); }
[[stitchable]] float4 make_f4_f2_f_f(float2 xy, float z, float w) { return float4(xy, z, w); }

// ============================================================================
// MARK: - Identity / Select
// ============================================================================

[[stitchable]] float identity_f(float x) { return x; }
[[stitchable]] float4 identity_f4(float4 x) { return x; }

// Select functions: consume unused input b, return a
[[stitchable]] float4 select_f4_f4(float4 a, float4 b) { return a; }
[[stitchable]] float4 select_f4_f2(float4 a, float2 b) { return a; }
[[stitchable]] float4 select_f4_f(float4 a, float b) { return a; }

} // namespace shadergraph
