// StdlibGenerated.swift
// Generated by gyb - do not edit directly

import Metal

// MARK: - Generated Stdlib Registration

extension ShaderGraph {
    /// Register generated arithmetic operations from the stdlib metallib
    func registerGeneratedStdlib(library: MTLLibrary) {
        // --- f (float) ---
        
        // Scalar-scalar operations
        registerFunction(named: "shadergraph::add_f_f", library: library, inputs: [.float, .float], output: .float)
        registerFunction(named: "shadergraph::sub_f_f", library: library, inputs: [.float, .float], output: .float)
        registerFunction(named: "shadergraph::mul_f_f", library: library, inputs: [.float, .float], output: .float)
        registerFunction(named: "shadergraph::div_f_f", library: library, inputs: [.float, .float], output: .float)

        // float2 vector-vector operations
        registerFunction(named: "shadergraph::add_f2_f2", library: library, inputs: [.float2, .float2], output: .float2)
        registerFunction(named: "shadergraph::sub_f2_f2", library: library, inputs: [.float2, .float2], output: .float2)
        registerFunction(named: "shadergraph::mul_f2_f2", library: library, inputs: [.float2, .float2], output: .float2)
        registerFunction(named: "shadergraph::div_f2_f2", library: library, inputs: [.float2, .float2], output: .float2)

        // float2 vector-scalar operations
        registerFunction(named: "shadergraph::add_f2_f", library: library, inputs: [.float2, .float], output: .float2)
        registerFunction(named: "shadergraph::sub_f2_f", library: library, inputs: [.float2, .float], output: .float2)
        registerFunction(named: "shadergraph::mul_f2_f", library: library, inputs: [.float2, .float], output: .float2)
        registerFunction(named: "shadergraph::div_f2_f", library: library, inputs: [.float2, .float], output: .float2)

        // float2 swizzles
        registerFunction(named: "shadergraph::swizzle_x_f2", library: library, inputs: [.float2], output: .float)
        registerFunction(named: "shadergraph::swizzle_y_f2", library: library, inputs: [.float2], output: .float)

        // float3 vector-vector operations
        registerFunction(named: "shadergraph::add_f3_f3", library: library, inputs: [.float3, .float3], output: .float3)
        registerFunction(named: "shadergraph::sub_f3_f3", library: library, inputs: [.float3, .float3], output: .float3)
        registerFunction(named: "shadergraph::mul_f3_f3", library: library, inputs: [.float3, .float3], output: .float3)
        registerFunction(named: "shadergraph::div_f3_f3", library: library, inputs: [.float3, .float3], output: .float3)

        // float3 vector-scalar operations
        registerFunction(named: "shadergraph::add_f3_f", library: library, inputs: [.float3, .float], output: .float3)
        registerFunction(named: "shadergraph::sub_f3_f", library: library, inputs: [.float3, .float], output: .float3)
        registerFunction(named: "shadergraph::mul_f3_f", library: library, inputs: [.float3, .float], output: .float3)
        registerFunction(named: "shadergraph::div_f3_f", library: library, inputs: [.float3, .float], output: .float3)

        // float3 swizzles
        registerFunction(named: "shadergraph::swizzle_x_f3", library: library, inputs: [.float3], output: .float)
        registerFunction(named: "shadergraph::swizzle_y_f3", library: library, inputs: [.float3], output: .float)
        registerFunction(named: "shadergraph::swizzle_z_f3", library: library, inputs: [.float3], output: .float)

        // float4 vector-vector operations
        registerFunction(named: "shadergraph::add_f4_f4", library: library, inputs: [.float4, .float4], output: .float4)
        registerFunction(named: "shadergraph::sub_f4_f4", library: library, inputs: [.float4, .float4], output: .float4)
        registerFunction(named: "shadergraph::mul_f4_f4", library: library, inputs: [.float4, .float4], output: .float4)
        registerFunction(named: "shadergraph::div_f4_f4", library: library, inputs: [.float4, .float4], output: .float4)

        // float4 vector-scalar operations
        registerFunction(named: "shadergraph::add_f4_f", library: library, inputs: [.float4, .float], output: .float4)
        registerFunction(named: "shadergraph::sub_f4_f", library: library, inputs: [.float4, .float], output: .float4)
        registerFunction(named: "shadergraph::mul_f4_f", library: library, inputs: [.float4, .float], output: .float4)
        registerFunction(named: "shadergraph::div_f4_f", library: library, inputs: [.float4, .float], output: .float4)

        // float4 swizzles
        registerFunction(named: "shadergraph::swizzle_x_f4", library: library, inputs: [.float4], output: .float)
        registerFunction(named: "shadergraph::swizzle_y_f4", library: library, inputs: [.float4], output: .float)
        registerFunction(named: "shadergraph::swizzle_z_f4", library: library, inputs: [.float4], output: .float)
        registerFunction(named: "shadergraph::swizzle_w_f4", library: library, inputs: [.float4], output: .float)

    }
}
